name: build
run-name: build
on:
  push:
    branches:
      - master
env:
  FORCE_COLOR: 1
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - id: build
        run: |
          true
      # - name: Notify Deployer
      #   if: always()
      #   uses: "./packages/deployer/actions/notify-pre-deploy"
      #   with:
      #     github-token: ${{ secrets.GITHUB_TOKEN }}
      #     outcome: ${{steps.build.outcome}}
